version: '3.8'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      FLASK_ENV: production
      FLASK_DEBUG: 'False'
    depends_on:
      - database

  database:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Kraujinieks123
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - my-db:/var/lib/mysql
      - ./db_seed.sql:/docker-entrypoint-initdb.d/01-seed.sql

volumes:
  my-db:
