version: '3.8'

services:
  web:
    environment:
      FLASK_DEBUG: 'True'
      FLASK_ENV: development
    restart: "no"
    volumes:
      - .:/app
  database:
    restart: "no"
    ports:
      - '3307:3306'
