version: '3.8'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      FLASK_ENV: production
      FLASK_DEBUG: 'False'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/login" ]
      interval: 5s
      timeout: 2s
      retries: 5
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Kraujinieks123
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - my-db:/var/lib/mysql
      - ./db_seed.sql:/docker-entrypoint-initdb.d/01-seed.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -pKraujinieks123 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
      # start_period: 30s
    restart: unless-stopped

volumes:
  my-db:
